backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "home-page",
            }
          - {
              label: Hero,
              name: hero,
              widget: object,
              fields:
                [
                  { label: "Hero Image", name: hero_image, widget: image },
                  {
                    label: "Hero Image alt",
                    name: hero_image_alt,
                    widget: string,
                    optional: true,
                  },
                  {
                    label: "Hero body",
                    name: hero_body,
                    widget: string,
                    optional: true,
                  },
                ],
            }
          - {
              label: "About section",
              name: about_section,
              widget: object,
              fields:
                [
                  {
                    label: "About heading",
                    name: about_heading,
                    widget: string,
                  },
                  { label: "About body", name: about_body, widget: markdown },
                ],
            }
          - {
              label: "Our Team section",
              name: our_team_section,
              widget: object,
              fields:
                [
                  {
                    label: "Our Team heading",
                    name: our_team_heading,
                    widget: string,
                  },
                  {
                    label: Avatar,
                    name: avatar,
                    widget: list,
                    fields:
                      [
                        { label: Portrait, name: portrait, widget: image },
                        { label: Caption, name: caption, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Secondary hero,
              name: secondary_hero,
              widget: object,
              fields:
                [
                  {
                    label: "Secondary Hero Image",
                    name: secondary_hero_image,
                    widget: image,
                  },
                  {
                    label: "Secondary Hero Image alt",
                    name: secondary_hero_image_alt,
                    widget: string,
                    optional: true,
                  },
                ],
            }
          - {
              label: "Our Process section",
              name: our_process_section,
              widget: object,
              fields:
                [
                  {
                    label: "Our Process heading",
                    name: our_process_heading,
                    widget: string,
                  },
                  {
                    label: "Our Process body",
                    name: our_process_body,
                    widget: markdown,
                  },
                  {
                    label: "Our Process image",
                    name: our_process_image,
                    widget: image,
                  },
                ],
            }
          - {
              label: "Our Services section",
              name: our_services_section,
              widget: object,
              fields:
                [
                  {
                    label: "Our Services heading",
                    name: our_services_heading,
                    widget: string,
                  },
                  {
                    label: "Our Services body",
                    name: our_services_body,
                    widget: markdown,
                  },
                  {
                    label: "Our Services list",
                    name: our_services_list,
                    widget: markdown,
                  },
                ],
            }
          - {
              label: Tertiary hero,
              name: tertiary_hero,
              widget: object,
              fields:
                [
                  {
                    label: "Tertiary Hero Image",
                    name: tertiary_hero_image,
                    widget: image,
                  },
                  {
                    label: "Tertiary Hero Image alt",
                    name: tertiary_hero_image_alt,
                    widget: string,
                    optional: true,
                  },
                ],
            }
          - {
              label: "Project section",
              name: project_section,
              widget: object,
              fields:
                [
                  {
                    label: "Project heading",
                    name: project_heading,
                    widget: string,
                  },
                  {
                    label: Project,
                    name: project,
                    widget: list,
                    fields:
                      [
                        {
                          label: "Project image",
                          name: project_image,
                          widget: image,
                        },
                        {
                          label: "Project image alt",
                          name: project_image_alt,
                          widget: string,
                        },
                        {
                          label: "Project details",
                          name: project_details,
                          widget: markdown,
                        },
                      ],
                  },
                ],
            }
          - { label: Title, name: title, widget: string }
          - { label: Heading, name: heading, widget: string }
          - { label: "Hero Image", name: hero_image, widget: image }
          - { label: Description, name: description, widget: string }
          - {
              label: Offerings,
              name: offerings,
              widget: object,
              fields:
                [
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Testimonials,
              name: testimonials,
              widget: list,
              fields:
                [
                  { label: Quote, name: quote, widget: string },
                  { label: Author, name: author, widget: string },
                ],
            }
          - { label: "Meta Title", name: "meta_title", widget: "string" }
          - {
              label: "Meta Description",
              name: "meta_description",
              widget: "text",
            }
      - file: "src/pages/pricing/index.md"
        label: "Pricing Page"
        name: "pricing"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "pricing-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - {
              label: Pricing,
              name: pricing,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: string },
                  {
                    label: Plans,
                    name: plans,
                    widget: list,
                    fields:
                      [
                        { label: Plan, name: plan, widget: string },
                        { label: Price, name: price, widget: string },
                        {
                          label: Description,
                          name: description,
                          widget: string,
                        },
                        { label: Items, name: items, widget: list },
                      ],
                  },
                ],
            }
          - { label: "Meta Title", name: "meta_title", widget: "string" }
          - {
              label: "Meta Description",
              name: "meta_description",
              widget: "text",
            }
      - file: "src/pages/contact/index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: "Meta Title", name: "meta_title", widget: "string" }
          - {
              label: "Meta Description",
              name: "meta_description",
              widget: "text",
            }
  - name: "portfolio"
    label: "Portfolio"
    folder: "src/pages/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "article-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover", name: "cover", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Meta Title", name: "meta_title", widget: "string" }
      - { label: "Meta Description", name: "meta_description", widget: "text" }
